export enum ProjectError {
  LIST_FETCH_FAILED = 'PROJECT_LIST_FETCH_FAILED',
  NOT_FOUND = 'PROJECT_NOT_FOUND',
  ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  DETAILS_FETCH_FAILED = 'PROJECT_DETAILS_FETCH_FAILED',
}
